package com.urdu_keyboard.utilityClasses

object RemoteConfigConstTest {
    // SOT-Ads-Visibility-Config
    const val RESUME_INTER_SPLASH = "RESUME_INTER_SPLASH"
    const val RESUME_OVERALL = "RESUME_OVERALL"
    const val BANNER_SPLASH = "BANNER_SPLASH"
    const val NATIVE_LANGUAGE_1 = "NATIVE_LANGUAGE_1"
    const val NATIVE_LANGUAGE_2 = "NATIVE_LANGUAGE_2"
    const val NATIVE_SURVEY_1 = "NATIVE_SURVEY_1"
    const val NATIVE_SURVEY_2 = "NATIVE_SURVEY_2"
    const val NATIVE_WALKTHROUGH_1 = "NATIVE_WALKTHROUGH_1"
    const val NATIVE_WALKTHROUGH_FULLSCR = "NATIVE_WALKTHROUGH_FULLSCR"
    const val NATIVE_WALKTHROUGH_3 = "NATIVE_WALKTHROUGH_3"

    // SOT-Ads-Mediation-Config
    const val RESUME_INTER_SPLASH_MED = "RESUME_INTER_SPLASH_MED"
    const val RESUME_OVERALL_MED = "RESUME_OVERALL_MED"
    const val BANNER_SPLASH_MED = "BANNER_SPLASH_MED"
    const val NATIVE_LANGUAGE_1_MED = "NATIVE_LANGUAGE_1_MED"
    const val NATIVE_LANGUAGE_2_MED = "NATIVE_LANGUAGE_2_MED"
    const val NATIVE_SURVEY_1_MED = "NATIVE_SURVEY_1_MED"
    const val NATIVE_SURVEY_2_MED = "NATIVE_SURVEY_2_MED"
    const val NATIVE_WALKTHROUGH_1_MED = "NATIVE_WALKTHROUGH_1_MED"
    const val NATIVE_WALKTHROUGH_FULLSCR_MED = "NATIVE_WALKTHROUGH_FULLSCR_MED"
    const val NATIVE_WALKTHROUGH_3_MED = "NATIVE_WALKTHROUGH_3_MED"

    const val TIMER_NATIVE_F_SRC = "TIMER_NATIVE_F_SRC"
}